### ISSUE TITLE
Armor Resetting Bug

### ISSUE THREAD

**Issue by Shockfire** [FishPhd/DewritoLauncher#34]
Dunno if this has been fixed yet or not, but there's an issue that people have been crying about on reddit a lot where the launcher resets your armor.

How to reproduce:
1. Start with a fresh config (armor all set to air_assault)
2. Run the launcher and set an armor piece to something else
3. Close the launcher and verify that the setting was changed in dewrito_prefs.cfg
4. Open and close the launcher without changing anything
5. Open dewrito_prefs.cfg and the armor will have been reset back to air_assault

**Comment by FishPhd** [comment]
Im going to redo when the launcher saves and loads the cfg because now that eldorito doesn't force close I can be a little more reckless. Seems to be an issue with the cfg not saving on close and causing an error to be thrown thus wiping the cfg to default.

Edit: Also I have heard the armor does not reset in the beta version so I am not going to focus on this until I hear another report.
